
		// This file is automatically generated
		export type ColorName = 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'muted' | 'tertiary';
		
		export interface Colors {
		  	primary: string;
secondary: string;
success: string;
danger: string;
warning: string;
info: string;
muted: string;
tertiary: string;
		}
  